// Code generated by wlgen; DO NOT EDIT.
package capturesession

import (
	"fmt"
	wayland "github.com/bnema/purego-libwayland/protocol/wayland"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var NeferwlCaptureManagerV1Interface *server.Interface
var NeferwlCaptureLayerV1Interface *server.Interface
var NeferwlCaptureSessionV1Interface *server.Interface

func init() {
	NeferwlCaptureManagerV1Interface = &server.Interface{Name: "neferwl_capture_manager_v1", Version: 1}
	NeferwlCaptureLayerV1Interface = &server.Interface{Name: "neferwl_capture_layer_v1", Version: 1}
	NeferwlCaptureSessionV1Interface = &server.Interface{Name: "neferwl_capture_session_v1", Version: 1}
	NeferwlCaptureManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "begin_session", Signature: "noiiiiuuu", Types: []*server.Interface{NeferwlCaptureSessionV1Interface, wayland.OutputInterface, nil, nil, nil, nil, nil, nil, nil}},
		{Name: "attach_surface", Signature: "nso", Types: []*server.Interface{NeferwlCaptureLayerV1Interface, nil, wayland.SurfaceInterface}},
	}
	NeferwlCaptureManagerV1Interface.Events = []server.Message{
		{Name: "workspace", Signature: "uussiiiiu", Types: []*server.Interface{nil, nil, nil, nil, nil, nil, nil, nil, nil}},
		{Name: "workspace_removed", Signature: "uu", Types: []*server.Interface{nil, nil}},
	}
	NeferwlCaptureLayerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	NeferwlCaptureLayerV1Interface.Events = []server.Message{
		{Name: "attached", Signature: "", Types: []*server.Interface{}},
		{Name: "failed", Signature: "u", Types: []*server.Interface{nil}},
		{Name: "detached", Signature: "u", Types: []*server.Interface{nil}},
	}
	NeferwlCaptureSessionV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "ping", Signature: "", Types: []*server.Interface{}},
	}
	NeferwlCaptureSessionV1Interface.Events = []server.Message{
		{Name: "state", Signature: "suiiiiuuuu", Types: []*server.Interface{nil, nil, nil, nil, nil, nil, nil, nil, nil, nil}},
		{Name: "stopped", Signature: "u", Types: []*server.Interface{nil}},
	}
	if err := server.NewInterfaces(NeferwlCaptureManagerV1Interface, NeferwlCaptureLayerV1Interface, NeferwlCaptureSessionV1Interface); err != nil {
		panic(err)
	}
}

// NeferwlCaptureManagerV1 private capture manager.
type NeferwlCaptureManagerV1 struct{ *server.Resource }

func WrapNeferwlCaptureManagerV1(r *server.Resource) *NeferwlCaptureManagerV1 {
	if r == nil {
		return nil
	}
	return &NeferwlCaptureManagerV1{r}
}

const NeferwlCaptureManagerV1RequestDestroy uint32 = 0
const NeferwlCaptureManagerV1RequestBeginSession uint32 = 1
const NeferwlCaptureManagerV1RequestAttachSurface uint32 = 2
const NeferwlCaptureManagerV1EventWorkspace uint32 = 0
const NeferwlCaptureManagerV1EventWorkspaceRemoved uint32 = 1

// NeferwlCaptureManagerV1Error .
type NeferwlCaptureManagerV1Error uint32

const (
	NeferwlCaptureManagerV1ErrorInvalidOutput     NeferwlCaptureManagerV1Error = 0
	NeferwlCaptureManagerV1ErrorInvalidRegion     NeferwlCaptureManagerV1Error = 1
	NeferwlCaptureManagerV1ErrorSurfaceRole       NeferwlCaptureManagerV1Error = 2
	NeferwlCaptureManagerV1ErrorInvalidLayer      NeferwlCaptureManagerV1Error = 3
	NeferwlCaptureManagerV1ErrorExclusiveKeyboard NeferwlCaptureManagerV1Error = 4
	NeferwlCaptureManagerV1ErrorInvalidSurface    NeferwlCaptureManagerV1Error = 5
)

// NeferwlCaptureManagerV1Handler handles neferwl_capture_manager_v1 requests.
type NeferwlCaptureManagerV1Handler interface {
	Destroy(self *NeferwlCaptureManagerV1)
	BeginSession(self *NeferwlCaptureManagerV1, id uint32, output *wayland.Output, x int32, y int32, width int32, height int32, workspaceHi uint32, workspaceLo uint32, record uint32)
	AttachSurface(self *NeferwlCaptureManagerV1, id uint32, token string, surface *wayland.Surface)
}

func NewNeferwlCaptureManagerV1(c server.Client, version int32, id uint32, h NeferwlCaptureManagerV1Handler) (*NeferwlCaptureManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for neferwl_capture_manager_v1")
	}
	var self *NeferwlCaptureManagerV1
	r, err := c.CreateResource(NeferwlCaptureManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.BeginSession(self, args[0].NewID(), wayland.WrapOutput(args[1].Resource()), args[2].Int(), args[3].Int(), args[4].Int(), args[5].Int(), args[6].Uint(), args[7].Uint(), args[8].Uint())
		case 2:
			h.AttachSurface(self, args[0].NewID(), args[1].String(), wayland.WrapSurface(args[2].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapNeferwlCaptureManagerV1(r)
	r.Data = self
	return self, nil
}

// SendWorkspace a workspace and its geometry.
func (self *NeferwlCaptureManagerV1) SendWorkspace(workspaceHi uint32, workspaceLo uint32, outputName string, name string, x int32, y int32, width int32, height int32, active uint32) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(NeferwlCaptureManagerV1EventWorkspace, server.Uint(workspaceHi), server.Uint(workspaceLo), server.String(&p, outputName, false), server.String(&p, name, false), server.Int(x), server.Int(y), server.Int(width), server.Int(height), server.Uint(active))
}

// SendWorkspaceRemoved a workspace is gone.
func (self *NeferwlCaptureManagerV1) SendWorkspaceRemoved(workspaceHi uint32, workspaceLo uint32) {
	self.PostEvent(NeferwlCaptureManagerV1EventWorkspaceRemoved, server.Uint(workspaceHi), server.Uint(workspaceLo))
}
func NewNeferwlCaptureManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(NeferwlCaptureManagerV1Interface, version, bind)
}

// NeferwlCaptureLayerV1 a layer surface attached to a capture session.
type NeferwlCaptureLayerV1 struct{ *server.Resource }

func WrapNeferwlCaptureLayerV1(r *server.Resource) *NeferwlCaptureLayerV1 {
	if r == nil {
		return nil
	}
	return &NeferwlCaptureLayerV1{r}
}

const NeferwlCaptureLayerV1RequestDestroy uint32 = 0
const NeferwlCaptureLayerV1EventAttached uint32 = 0
const NeferwlCaptureLayerV1EventFailed uint32 = 1
const NeferwlCaptureLayerV1EventDetached uint32 = 2

// NeferwlCaptureLayerV1Failure .
type NeferwlCaptureLayerV1Failure uint32

const (
	NeferwlCaptureLayerV1FailureUnknownToken    NeferwlCaptureLayerV1Failure = 0
	NeferwlCaptureLayerV1FailureUnauthorized    NeferwlCaptureLayerV1Failure = 1
	NeferwlCaptureLayerV1FailureTooManyLayers   NeferwlCaptureLayerV1Failure = 2
	NeferwlCaptureLayerV1FailureAlreadyAttached NeferwlCaptureLayerV1Failure = 3
	NeferwlCaptureLayerV1FailureSessionEnded    NeferwlCaptureLayerV1Failure = 4
	NeferwlCaptureLayerV1FailureLayerDestroyed  NeferwlCaptureLayerV1Failure = 5
)

// NeferwlCaptureLayerV1DetachReason .
type NeferwlCaptureLayerV1DetachReason uint32

const (
	NeferwlCaptureLayerV1DetachReasonSessionEnded   NeferwlCaptureLayerV1DetachReason = 0
	NeferwlCaptureLayerV1DetachReasonLayerDestroyed NeferwlCaptureLayerV1DetachReason = 1
)

// NeferwlCaptureLayerV1Handler handles neferwl_capture_layer_v1 requests.
type NeferwlCaptureLayerV1Handler interface {
	Destroy(self *NeferwlCaptureLayerV1)
}

func NewNeferwlCaptureLayerV1(c server.Client, version int32, id uint32, h NeferwlCaptureLayerV1Handler) (*NeferwlCaptureLayerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for neferwl_capture_layer_v1")
	}
	var self *NeferwlCaptureLayerV1
	r, err := c.CreateResource(NeferwlCaptureLayerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapNeferwlCaptureLayerV1(r)
	r.Data = self
	return self, nil
}

// SendAttached the layer is part of the session.
func (self *NeferwlCaptureLayerV1) SendAttached() {
	self.PostEvent(NeferwlCaptureLayerV1EventAttached)
}

// SendFailed the attachment was refused.
func (self *NeferwlCaptureLayerV1) SendFailed(reason uint32) {
	self.PostEvent(NeferwlCaptureLayerV1EventFailed, server.Uint(reason))
}

// SendDetached the layer left the session.
func (self *NeferwlCaptureLayerV1) SendDetached(reason uint32) {
	self.PostEvent(NeferwlCaptureLayerV1EventDetached, server.Uint(reason))
}
func NewNeferwlCaptureLayerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(NeferwlCaptureLayerV1Interface, version, bind)
}

// NeferwlCaptureSessionV1 one private capture session.
type NeferwlCaptureSessionV1 struct{ *server.Resource }

func WrapNeferwlCaptureSessionV1(r *server.Resource) *NeferwlCaptureSessionV1 {
	if r == nil {
		return nil
	}
	return &NeferwlCaptureSessionV1{r}
}

const NeferwlCaptureSessionV1RequestDestroy uint32 = 0
const NeferwlCaptureSessionV1RequestPing uint32 = 1
const NeferwlCaptureSessionV1EventState uint32 = 0
const NeferwlCaptureSessionV1EventStopped uint32 = 1

// NeferwlCaptureSessionV1StopReason .
type NeferwlCaptureSessionV1StopReason uint32

const (
	NeferwlCaptureSessionV1StopReasonRequested       NeferwlCaptureSessionV1StopReason = 0
	NeferwlCaptureSessionV1StopReasonOutputGone      NeferwlCaptureSessionV1StopReason = 1
	NeferwlCaptureSessionV1StopReasonOutputOff       NeferwlCaptureSessionV1StopReason = 2
	NeferwlCaptureSessionV1StopReasonPingTimeout     NeferwlCaptureSessionV1StopReason = 3
	NeferwlCaptureSessionV1StopReasonWorkspaceGone   NeferwlCaptureSessionV1StopReason = 5
	NeferwlCaptureSessionV1StopReasonBusy            NeferwlCaptureSessionV1StopReason = 6
	NeferwlCaptureSessionV1StopReasonInvalidRegion   NeferwlCaptureSessionV1StopReason = 7
	NeferwlCaptureSessionV1StopReasonUnauthorized    NeferwlCaptureSessionV1StopReason = 8
	NeferwlCaptureSessionV1StopReasonTooManyExcluded NeferwlCaptureSessionV1StopReason = 9
)

// NeferwlCaptureSessionV1Handler handles neferwl_capture_session_v1 requests.
type NeferwlCaptureSessionV1Handler interface {
	Destroy(self *NeferwlCaptureSessionV1)
	Ping(self *NeferwlCaptureSessionV1)
}

func NewNeferwlCaptureSessionV1(c server.Client, version int32, id uint32, h NeferwlCaptureSessionV1Handler) (*NeferwlCaptureSessionV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for neferwl_capture_session_v1")
	}
	var self *NeferwlCaptureSessionV1
	r, err := c.CreateResource(NeferwlCaptureSessionV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.Ping(self)
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapNeferwlCaptureSessionV1(r)
	r.Data = self
	return self, nil
}

// SendState what the compositor decided.
func (self *NeferwlCaptureSessionV1) SendState(token string, active uint32, x int32, y int32, width int32, height int32, workspaceHi uint32, workspaceLo uint32, revisionHi uint32, revisionLo uint32) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(NeferwlCaptureSessionV1EventState, server.String(&p, token, false), server.Uint(active), server.Int(x), server.Int(y), server.Int(width), server.Int(height), server.Uint(workspaceHi), server.Uint(workspaceLo), server.Uint(revisionHi), server.Uint(revisionLo))
}

// SendStopped the session ended.
func (self *NeferwlCaptureSessionV1) SendStopped(reason uint32) {
	self.PostEvent(NeferwlCaptureSessionV1EventStopped, server.Uint(reason))
}
func NewNeferwlCaptureSessionV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(NeferwlCaptureSessionV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *NeferwlCaptureManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *NeferwlCaptureLayerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *NeferwlCaptureSessionV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
