// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddc

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockbus creates a new instance of mockbus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbus(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbus {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockbus{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockbus is an autogenerated mock type for the bus type
type mockbus struct {
	mock.Mock
}

type mockbus_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbus) EXPECT() *mockbus_Expecter {
	return &mockbus_Expecter{mock: &_m.Mock}
}

// close provides a mock function for the type mockbus
func (_mock *mockbus) close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbus_close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'close'
type mockbus_close_Call struct {
	*mock.Call
}

// close is a helper method to define mock.On call
func (_e *mockbus_Expecter) close() *mockbus_close_Call {
	return &mockbus_close_Call{Call: _e.mock.On("close")}
}

func (_c *mockbus_close_Call) Run(run func()) *mockbus_close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockbus_close_Call) Return(err error) *mockbus_close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbus_close_Call) RunAndReturn(run func() error) *mockbus_close_Call {
	_c.Call.Return(run)
	return _c
}

// read provides a mock function for the type mockbus
func (_mock *mockbus) read(addr uint16, b []byte) error {
	ret := _mock.Called(addr, b)

	if len(ret) == 0 {
		panic("no return value specified for read")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint16, []byte) error); ok {
		r0 = returnFunc(addr, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbus_read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'read'
type mockbus_read_Call struct {
	*mock.Call
}

// read is a helper method to define mock.On call
//   - addr uint16
//   - b []byte
func (_e *mockbus_Expecter) read(addr any, b any) *mockbus_read_Call {
	return &mockbus_read_Call{Call: _e.mock.On("read", addr, b)}
}

func (_c *mockbus_read_Call) Run(run func(addr uint16, b []byte)) *mockbus_read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbus_read_Call) Return(err error) *mockbus_read_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbus_read_Call) RunAndReturn(run func(addr uint16, b []byte) error) *mockbus_read_Call {
	_c.Call.Return(run)
	return _c
}

// write provides a mock function for the type mockbus
func (_mock *mockbus) write(addr uint16, b []byte) error {
	ret := _mock.Called(addr, b)

	if len(ret) == 0 {
		panic("no return value specified for write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint16, []byte) error); ok {
		r0 = returnFunc(addr, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockbus_write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'write'
type mockbus_write_Call struct {
	*mock.Call
}

// write is a helper method to define mock.On call
//   - addr uint16
//   - b []byte
func (_e *mockbus_Expecter) write(addr any, b any) *mockbus_write_Call {
	return &mockbus_write_Call{Call: _e.mock.On("write", addr, b)}
}

func (_c *mockbus_write_Call) Run(run func(addr uint16, b []byte)) *mockbus_write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbus_write_Call) Return(err error) *mockbus_write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockbus_write_Call) RunAndReturn(run func(addr uint16, b []byte) error) *mockbus_write_Call {
	_c.Call.Return(run)
	return _c
}
