// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Notify(summary string, body string) {
	_mock.Called(summary, body)
	return
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - summary string
//   - body string
func (_e *MockNotifier_Expecter) Notify(summary any, body any) *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify", summary, body)}
}

func (_c *MockNotifier_Notify_Call) Run(run func(summary string, body string)) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return() *MockNotifier_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func(summary string, body string)) *MockNotifier_Notify_Call {
	_c.Run(run)
	return _c
}

// NewMockOutputScaleStore creates a new instance of MockOutputScaleStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputScaleStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputScaleStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOutputScaleStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOutputScaleStore is an autogenerated mock type for the OutputScaleStore type
type MockOutputScaleStore struct {
	mock.Mock
}

type MockOutputScaleStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputScaleStore) EXPECT() *MockOutputScaleStore_Expecter {
	return &MockOutputScaleStore_Expecter{mock: &_m.Mock}
}

// SaveOutputScale provides a mock function for the type MockOutputScaleStore
func (_mock *MockOutputScaleStore) SaveOutputScale(output string, scale float64) error {
	ret := _mock.Called(output, scale)

	if len(ret) == 0 {
		panic("no return value specified for SaveOutputScale")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = returnFunc(output, scale)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutputScaleStore_SaveOutputScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOutputScale'
type MockOutputScaleStore_SaveOutputScale_Call struct {
	*mock.Call
}

// SaveOutputScale is a helper method to define mock.On call
//   - output string
//   - scale float64
func (_e *MockOutputScaleStore_Expecter) SaveOutputScale(output any, scale any) *MockOutputScaleStore_SaveOutputScale_Call {
	return &MockOutputScaleStore_SaveOutputScale_Call{Call: _e.mock.On("SaveOutputScale", output, scale)}
}

func (_c *MockOutputScaleStore_SaveOutputScale_Call) Run(run func(output string, scale float64)) *MockOutputScaleStore_SaveOutputScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputScaleStore_SaveOutputScale_Call) Return(err error) *MockOutputScaleStore_SaveOutputScale_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutputScaleStore_SaveOutputScale_Call) RunAndReturn(run func(output string, scale float64) error) *MockOutputScaleStore_SaveOutputScale_Call {
	_c.Call.Return(run)
	return _c
}
