// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"image"

	"github.com/bnema/nefertty/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRenderer
func (_mock *MockRenderer) Close() {
	_mock.Called()
	return
}

// MockRenderer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRenderer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRenderer_Expecter) Close() *MockRenderer_Close_Call {
	return &MockRenderer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRenderer_Close_Call) Run(run func()) *MockRenderer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenderer_Close_Call) Return() *MockRenderer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenderer_Close_Call) RunAndReturn(run func()) *MockRenderer_Close_Call {
	_c.Run(run)
	return _c
}

// CopyBGRX provides a mock function for the type MockRenderer
func (_mock *MockRenderer) CopyBGRX(dst []byte, pitch int) {
	_mock.Called(dst, pitch)
	return
}

// MockRenderer_CopyBGRX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyBGRX'
type MockRenderer_CopyBGRX_Call struct {
	*mock.Call
}

// CopyBGRX is a helper method to define mock.On call
//   - dst []byte
//   - pitch int
func (_e *MockRenderer_Expecter) CopyBGRX(dst any, pitch any) *MockRenderer_CopyBGRX_Call {
	return &MockRenderer_CopyBGRX_Call{Call: _e.mock.On("CopyBGRX", dst, pitch)}
}

func (_c *MockRenderer_CopyBGRX_Call) Run(run func(dst []byte, pitch int)) *MockRenderer_CopyBGRX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenderer_CopyBGRX_Call) Return() *MockRenderer_CopyBGRX_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenderer_CopyBGRX_Call) RunAndReturn(run func(dst []byte, pitch int)) *MockRenderer_CopyBGRX_Call {
	_c.Run(run)
	return _c
}

// Pixels provides a mock function for the type MockRenderer
func (_mock *MockRenderer) Pixels() *image.RGBA {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pixels")
	}

	var r0 *image.RGBA
	if returnFunc, ok := ret.Get(0).(func() *image.RGBA); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.RGBA)
		}
	}
	return r0
}

// MockRenderer_Pixels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pixels'
type MockRenderer_Pixels_Call struct {
	*mock.Call
}

// Pixels is a helper method to define mock.On call
func (_e *MockRenderer_Expecter) Pixels() *MockRenderer_Pixels_Call {
	return &MockRenderer_Pixels_Call{Call: _e.mock.On("Pixels")}
}

func (_c *MockRenderer_Pixels_Call) Run(run func()) *MockRenderer_Pixels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenderer_Pixels_Call) Return(rGBA *image.RGBA) *MockRenderer_Pixels_Call {
	_c.Call.Return(rGBA)
	return _c
}

func (_c *MockRenderer_Pixels_Call) RunAndReturn(run func() *image.RGBA) *MockRenderer_Pixels_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function for the type MockRenderer
func (_mock *MockRenderer) Render(scene ports.Scene, windowIDToSurfaceContent map[ports.WindowID]ports.SurfaceContent) error {
	ret := _mock.Called(scene, windowIDToSurfaceContent)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ports.Scene, map[ports.WindowID]ports.SurfaceContent) error); ok {
		r0 = returnFunc(scene, windowIDToSurfaceContent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - scene ports.Scene
//   - windowIDToSurfaceContent map[ports.WindowID]ports.SurfaceContent
func (_e *MockRenderer_Expecter) Render(scene any, windowIDToSurfaceContent any) *MockRenderer_Render_Call {
	return &MockRenderer_Render_Call{Call: _e.mock.On("Render", scene, windowIDToSurfaceContent)}
}

func (_c *MockRenderer_Render_Call) Run(run func(scene ports.Scene, windowIDToSurfaceContent map[ports.WindowID]ports.SurfaceContent)) *MockRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.Scene
		if args[0] != nil {
			arg0 = args[0].(ports.Scene)
		}
		var arg1 map[ports.WindowID]ports.SurfaceContent
		if args[1] != nil {
			arg1 = args[1].(map[ports.WindowID]ports.SurfaceContent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenderer_Render_Call) Return(err error) *MockRenderer_Render_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenderer_Render_Call) RunAndReturn(run func(scene ports.Scene, windowIDToSurfaceContent map[ports.WindowID]ports.SurfaceContent) error) *MockRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeat creates a new instance of MockSeat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeat {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSeat{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSeat is an autogenerated mock type for the Seat type
type MockSeat struct {
	mock.Mock
}

type MockSeat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeat) EXPECT() *MockSeat_Expecter {
	return &MockSeat_Expecter{mock: &_m.Mock}
}

// CloseDevice provides a mock function for the type MockSeat
func (_mock *MockSeat) CloseDevice(fd int) {
	_mock.Called(fd)
	return
}

// MockSeat_CloseDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDevice'
type MockSeat_CloseDevice_Call struct {
	*mock.Call
}

// CloseDevice is a helper method to define mock.On call
//   - fd int
func (_e *MockSeat_Expecter) CloseDevice(fd any) *MockSeat_CloseDevice_Call {
	return &MockSeat_CloseDevice_Call{Call: _e.mock.On("CloseDevice", fd)}
}

func (_c *MockSeat_CloseDevice_Call) Run(run func(fd int)) *MockSeat_CloseDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeat_CloseDevice_Call) Return() *MockSeat_CloseDevice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeat_CloseDevice_Call) RunAndReturn(run func(fd int)) *MockSeat_CloseDevice_Call {
	_c.Run(run)
	return _c
}

// OpenDevice provides a mock function for the type MockSeat
func (_mock *MockSeat) OpenDevice(path string) (int, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for OpenDevice")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeat_OpenDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDevice'
type MockSeat_OpenDevice_Call struct {
	*mock.Call
}

// OpenDevice is a helper method to define mock.On call
//   - path string
func (_e *MockSeat_Expecter) OpenDevice(path any) *MockSeat_OpenDevice_Call {
	return &MockSeat_OpenDevice_Call{Call: _e.mock.On("OpenDevice", path)}
}

func (_c *MockSeat_OpenDevice_Call) Run(run func(path string)) *MockSeat_OpenDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeat_OpenDevice_Call) Return(n int, err error) *MockSeat_OpenDevice_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSeat_OpenDevice_Call) RunAndReturn(run func(path string) (int, error)) *MockSeat_OpenDevice_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchVT provides a mock function for the type MockSeat
func (_mock *MockSeat) SwitchVT(vt int) {
	_mock.Called(vt)
	return
}

// MockSeat_SwitchVT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchVT'
type MockSeat_SwitchVT_Call struct {
	*mock.Call
}

// SwitchVT is a helper method to define mock.On call
//   - vt int
func (_e *MockSeat_Expecter) SwitchVT(vt any) *MockSeat_SwitchVT_Call {
	return &MockSeat_SwitchVT_Call{Call: _e.mock.On("SwitchVT", vt)}
}

func (_c *MockSeat_SwitchVT_Call) Run(run func(vt int)) *MockSeat_SwitchVT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeat_SwitchVT_Call) Return() *MockSeat_SwitchVT_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeat_SwitchVT_Call) RunAndReturn(run func(vt int)) *MockSeat_SwitchVT_Call {
	_c.Run(run)
	return _c
}
