// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockcursor creates a new instance of mockcursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcursor {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockcursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockcursor is an autogenerated mock type for the cursor type
type mockcursor struct {
	mock.Mock
}

type mockcursor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcursor) EXPECT() *mockcursor_Expecter {
	return &mockcursor_Expecter{mock: &_m.Mock}
}

// Hide provides a mock function for the type mockcursor
func (_mock *mockcursor) Hide() {
	_mock.Called()
	return
}

// mockcursor_Hide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hide'
type mockcursor_Hide_Call struct {
	*mock.Call
}

// Hide is a helper method to define mock.On call
func (_e *mockcursor_Expecter) Hide() *mockcursor_Hide_Call {
	return &mockcursor_Hide_Call{Call: _e.mock.On("Hide")}
}

func (_c *mockcursor_Hide_Call) Run(run func()) *mockcursor_Hide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcursor_Hide_Call) Return() *mockcursor_Hide_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockcursor_Hide_Call) RunAndReturn(run func()) *mockcursor_Hide_Call {
	_c.Run(run)
	return _c
}

// Move provides a mock function for the type mockcursor
func (_mock *mockcursor) Move(x float64, y float64) {
	_mock.Called(x, y)
	return
}

// mockcursor_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type mockcursor_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - x float64
//   - y float64
func (_e *mockcursor_Expecter) Move(x any, y any) *mockcursor_Move_Call {
	return &mockcursor_Move_Call{Call: _e.mock.On("Move", x, y)}
}

func (_c *mockcursor_Move_Call) Run(run func(x float64, y float64)) *mockcursor_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcursor_Move_Call) Return() *mockcursor_Move_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockcursor_Move_Call) RunAndReturn(run func(x float64, y float64)) *mockcursor_Move_Call {
	_c.Run(run)
	return _c
}
