// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"os"

	"github.com/bnema/neferwl/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// newMockleaseInventoryCard creates a new instance of mockleaseInventoryCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockleaseInventoryCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockleaseInventoryCard {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockleaseInventoryCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockleaseInventoryCard is an autogenerated mock type for the leaseInventoryCard type
type mockleaseInventoryCard struct {
	mock.Mock
}

type mockleaseInventoryCard_Expecter struct {
	mock *mock.Mock
}

func (_m *mockleaseInventoryCard) EXPECT() *mockleaseInventoryCard_Expecter {
	return &mockleaseInventoryCard_Expecter{mock: &_m.Mock}
}

// ClientFD provides a mock function for the type mockleaseInventoryCard
func (_mock *mockleaseInventoryCard) ClientFD() (*os.File, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientFD")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*os.File, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *os.File); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockleaseInventoryCard_ClientFD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientFD'
type mockleaseInventoryCard_ClientFD_Call struct {
	*mock.Call
}

// ClientFD is a helper method to define mock.On call
func (_e *mockleaseInventoryCard_Expecter) ClientFD() *mockleaseInventoryCard_ClientFD_Call {
	return &mockleaseInventoryCard_ClientFD_Call{Call: _e.mock.On("ClientFD")}
}

func (_c *mockleaseInventoryCard_ClientFD_Call) Run(run func()) *mockleaseInventoryCard_ClientFD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockleaseInventoryCard_ClientFD_Call) Return(file *os.File, err error) *mockleaseInventoryCard_ClientFD_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *mockleaseInventoryCard_ClientFD_Call) RunAndReturn(run func() (*os.File, error)) *mockleaseInventoryCard_ClientFD_Call {
	_c.Call.Return(run)
	return _c
}

// FinishedLeases provides a mock function for the type mockleaseInventoryCard
func (_mock *mockleaseInventoryCard) FinishedLeases() []uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FinishedLeases")
	}

	var r0 []uint32
	if returnFunc, ok := ret.Get(0).(func() []uint32); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}
	return r0
}

// mockleaseInventoryCard_FinishedLeases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishedLeases'
type mockleaseInventoryCard_FinishedLeases_Call struct {
	*mock.Call
}

// FinishedLeases is a helper method to define mock.On call
func (_e *mockleaseInventoryCard_Expecter) FinishedLeases() *mockleaseInventoryCard_FinishedLeases_Call {
	return &mockleaseInventoryCard_FinishedLeases_Call{Call: _e.mock.On("FinishedLeases")}
}

func (_c *mockleaseInventoryCard_FinishedLeases_Call) Run(run func()) *mockleaseInventoryCard_FinishedLeases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockleaseInventoryCard_FinishedLeases_Call) Return(uint32s []uint32) *mockleaseInventoryCard_FinishedLeases_Call {
	_c.Call.Return(uint32s)
	return _c
}

func (_c *mockleaseInventoryCard_FinishedLeases_Call) RunAndReturn(run func() []uint32) *mockleaseInventoryCard_FinishedLeases_Call {
	_c.Call.Return(run)
	return _c
}

// Leasable provides a mock function for the type mockleaseInventoryCard
func (_mock *mockleaseInventoryCard) Leasable() []ports.LeaseConnector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Leasable")
	}

	var r0 []ports.LeaseConnector
	if returnFunc, ok := ret.Get(0).(func() []ports.LeaseConnector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.LeaseConnector)
		}
	}
	return r0
}

// mockleaseInventoryCard_Leasable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leasable'
type mockleaseInventoryCard_Leasable_Call struct {
	*mock.Call
}

// Leasable is a helper method to define mock.On call
func (_e *mockleaseInventoryCard_Expecter) Leasable() *mockleaseInventoryCard_Leasable_Call {
	return &mockleaseInventoryCard_Leasable_Call{Call: _e.mock.On("Leasable")}
}

func (_c *mockleaseInventoryCard_Leasable_Call) Run(run func()) *mockleaseInventoryCard_Leasable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockleaseInventoryCard_Leasable_Call) Return(leaseConnectors []ports.LeaseConnector) *mockleaseInventoryCard_Leasable_Call {
	_c.Call.Return(leaseConnectors)
	return _c
}

func (_c *mockleaseInventoryCard_Leasable_Call) RunAndReturn(run func() []ports.LeaseConnector) *mockleaseInventoryCard_Leasable_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type mockleaseInventoryCard
func (_mock *mockleaseInventoryCard) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockleaseInventoryCard_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type mockleaseInventoryCard_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *mockleaseInventoryCard_Expecter) Path() *mockleaseInventoryCard_Path_Call {
	return &mockleaseInventoryCard_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *mockleaseInventoryCard_Path_Call) Run(run func()) *mockleaseInventoryCard_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockleaseInventoryCard_Path_Call) Return(s string) *mockleaseInventoryCard_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockleaseInventoryCard_Path_Call) RunAndReturn(run func() string) *mockleaseInventoryCard_Path_Call {
	_c.Call.Return(run)
	return _c
}
