// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockseatDisablePreparer creates a new instance of mockseatDisablePreparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockseatDisablePreparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockseatDisablePreparer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockseatDisablePreparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockseatDisablePreparer is an autogenerated mock type for the seatDisablePreparer type
type mockseatDisablePreparer struct {
	mock.Mock
}

type mockseatDisablePreparer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockseatDisablePreparer) EXPECT() *mockseatDisablePreparer_Expecter {
	return &mockseatDisablePreparer_Expecter{mock: &_m.Mock}
}

// PrepareSeatDisable provides a mock function for the type mockseatDisablePreparer
func (_mock *mockseatDisablePreparer) PrepareSeatDisable(timeout time.Duration) bool {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for PrepareSeatDisable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(time.Duration) bool); ok {
		r0 = returnFunc(timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockseatDisablePreparer_PrepareSeatDisable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareSeatDisable'
type mockseatDisablePreparer_PrepareSeatDisable_Call struct {
	*mock.Call
}

// PrepareSeatDisable is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *mockseatDisablePreparer_Expecter) PrepareSeatDisable(timeout any) *mockseatDisablePreparer_PrepareSeatDisable_Call {
	return &mockseatDisablePreparer_PrepareSeatDisable_Call{Call: _e.mock.On("PrepareSeatDisable", timeout)}
}

func (_c *mockseatDisablePreparer_PrepareSeatDisable_Call) Run(run func(timeout time.Duration)) *mockseatDisablePreparer_PrepareSeatDisable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockseatDisablePreparer_PrepareSeatDisable_Call) Return(b bool) *mockseatDisablePreparer_PrepareSeatDisable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockseatDisablePreparer_PrepareSeatDisable_Call) RunAndReturn(run func(timeout time.Duration) bool) *mockseatDisablePreparer_PrepareSeatDisable_Call {
	_c.Call.Return(run)
	return _c
}
