// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// newMocksecurityLeaseCard creates a new instance of mocksecurityLeaseCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksecurityLeaseCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksecurityLeaseCard {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mocksecurityLeaseCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mocksecurityLeaseCard is an autogenerated mock type for the securityLeaseCard type
type mocksecurityLeaseCard struct {
	mock.Mock
}

type mocksecurityLeaseCard_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksecurityLeaseCard) EXPECT() *mocksecurityLeaseCard_Expecter {
	return &mocksecurityLeaseCard_Expecter{mock: &_m.Mock}
}

// Lease provides a mock function for the type mocksecurityLeaseCard
func (_mock *mocksecurityLeaseCard) Lease(strings []string) (*os.File, uint32, error) {
	ret := _mock.Called(strings)

	if len(ret) == 0 {
		panic("no return value specified for Lease")
	}

	var r0 *os.File
	var r1 uint32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]string) (*os.File, uint32, error)); ok {
		return returnFunc(strings)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) *os.File); ok {
		r0 = returnFunc(strings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) uint32); ok {
		r1 = returnFunc(strings)
	} else {
		r1 = ret.Get(1).(uint32)
	}
	if returnFunc, ok := ret.Get(2).(func([]string) error); ok {
		r2 = returnFunc(strings)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mocksecurityLeaseCard_Lease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lease'
type mocksecurityLeaseCard_Lease_Call struct {
	*mock.Call
}

// Lease is a helper method to define mock.On call
//   - strings []string
func (_e *mocksecurityLeaseCard_Expecter) Lease(strings any) *mocksecurityLeaseCard_Lease_Call {
	return &mocksecurityLeaseCard_Lease_Call{Call: _e.mock.On("Lease", strings)}
}

func (_c *mocksecurityLeaseCard_Lease_Call) Run(run func(strings []string)) *mocksecurityLeaseCard_Lease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksecurityLeaseCard_Lease_Call) Return(file *os.File, v uint32, err error) *mocksecurityLeaseCard_Lease_Call {
	_c.Call.Return(file, v, err)
	return _c
}

func (_c *mocksecurityLeaseCard_Lease_Call) RunAndReturn(run func(strings []string) (*os.File, uint32, error)) *mocksecurityLeaseCard_Lease_Call {
	_c.Call.Return(run)
	return _c
}

// LeaseIDs provides a mock function for the type mocksecurityLeaseCard
func (_mock *mocksecurityLeaseCard) LeaseIDs() []uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LeaseIDs")
	}

	var r0 []uint32
	if returnFunc, ok := ret.Get(0).(func() []uint32); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}
	return r0
}

// mocksecurityLeaseCard_LeaseIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaseIDs'
type mocksecurityLeaseCard_LeaseIDs_Call struct {
	*mock.Call
}

// LeaseIDs is a helper method to define mock.On call
func (_e *mocksecurityLeaseCard_Expecter) LeaseIDs() *mocksecurityLeaseCard_LeaseIDs_Call {
	return &mocksecurityLeaseCard_LeaseIDs_Call{Call: _e.mock.On("LeaseIDs")}
}

func (_c *mocksecurityLeaseCard_LeaseIDs_Call) Run(run func()) *mocksecurityLeaseCard_LeaseIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksecurityLeaseCard_LeaseIDs_Call) Return(uint32s []uint32) *mocksecurityLeaseCard_LeaseIDs_Call {
	_c.Call.Return(uint32s)
	return _c
}

func (_c *mocksecurityLeaseCard_LeaseIDs_Call) RunAndReturn(run func() []uint32) *mocksecurityLeaseCard_LeaseIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type mocksecurityLeaseCard
func (_mock *mocksecurityLeaseCard) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mocksecurityLeaseCard_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type mocksecurityLeaseCard_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *mocksecurityLeaseCard_Expecter) Path() *mocksecurityLeaseCard_Path_Call {
	return &mocksecurityLeaseCard_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *mocksecurityLeaseCard_Path_Call) Run(run func()) *mocksecurityLeaseCard_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksecurityLeaseCard_Path_Call) Return(s string) *mocksecurityLeaseCard_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mocksecurityLeaseCard_Path_Call) RunAndReturn(run func() string) *mocksecurityLeaseCard_Path_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type mocksecurityLeaseCard
func (_mock *mocksecurityLeaseCard) Revoke(v uint32) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksecurityLeaseCard_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type mocksecurityLeaseCard_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - v uint32
func (_e *mocksecurityLeaseCard_Expecter) Revoke(v any) *mocksecurityLeaseCard_Revoke_Call {
	return &mocksecurityLeaseCard_Revoke_Call{Call: _e.mock.On("Revoke", v)}
}

func (_c *mocksecurityLeaseCard_Revoke_Call) Run(run func(v uint32)) *mocksecurityLeaseCard_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksecurityLeaseCard_Revoke_Call) Return(err error) *mocksecurityLeaseCard_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksecurityLeaseCard_Revoke_Call) RunAndReturn(run func(v uint32) error) *mocksecurityLeaseCard_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
