// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vulkan

import (
	"github.com/bnema/purego-vulkan/vulkan"
	mock "github.com/stretchr/testify/mock"
)

// newMockcaptureSync creates a new instance of mockcaptureSync. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcaptureSync(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcaptureSync {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockcaptureSync{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockcaptureSync is an autogenerated mock type for the captureSync type
type mockcaptureSync struct {
	mock.Mock
}

type mockcaptureSync_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcaptureSync) EXPECT() *mockcaptureSync_Expecter {
	return &mockcaptureSync_Expecter{mock: &_m.Mock}
}

// destroySemaphore provides a mock function for the type mockcaptureSync
func (_mock *mockcaptureSync) destroySemaphore(s vulkan.Semaphore) {
	_mock.Called(s)
	return
}

// mockcaptureSync_destroySemaphore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'destroySemaphore'
type mockcaptureSync_destroySemaphore_Call struct {
	*mock.Call
}

// destroySemaphore is a helper method to define mock.On call
//   - s vulkan.Semaphore
func (_e *mockcaptureSync_Expecter) destroySemaphore(s any) *mockcaptureSync_destroySemaphore_Call {
	return &mockcaptureSync_destroySemaphore_Call{Call: _e.mock.On("destroySemaphore", s)}
}

func (_c *mockcaptureSync_destroySemaphore_Call) Run(run func(s vulkan.Semaphore)) *mockcaptureSync_destroySemaphore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 vulkan.Semaphore
		if args[0] != nil {
			arg0 = args[0].(vulkan.Semaphore)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcaptureSync_destroySemaphore_Call) Return() *mockcaptureSync_destroySemaphore_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockcaptureSync_destroySemaphore_Call) RunAndReturn(run func(s vulkan.Semaphore)) *mockcaptureSync_destroySemaphore_Call {
	_c.Run(run)
	return _c
}

// exportSyncFD provides a mock function for the type mockcaptureSync
func (_mock *mockcaptureSync) exportSyncFD(s vulkan.Semaphore) (int32, vulkan.Result) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for exportSyncFD")
	}

	var r0 int32
	var r1 vulkan.Result
	if returnFunc, ok := ret.Get(0).(func(vulkan.Semaphore) (int32, vulkan.Result)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(vulkan.Semaphore) int32); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(vulkan.Semaphore) vulkan.Result); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(vulkan.Result)
	}
	return r0, r1
}

// mockcaptureSync_exportSyncFD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'exportSyncFD'
type mockcaptureSync_exportSyncFD_Call struct {
	*mock.Call
}

// exportSyncFD is a helper method to define mock.On call
//   - s vulkan.Semaphore
func (_e *mockcaptureSync_Expecter) exportSyncFD(s any) *mockcaptureSync_exportSyncFD_Call {
	return &mockcaptureSync_exportSyncFD_Call{Call: _e.mock.On("exportSyncFD", s)}
}

func (_c *mockcaptureSync_exportSyncFD_Call) Run(run func(s vulkan.Semaphore)) *mockcaptureSync_exportSyncFD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 vulkan.Semaphore
		if args[0] != nil {
			arg0 = args[0].(vulkan.Semaphore)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcaptureSync_exportSyncFD_Call) Return(n int32, result vulkan.Result) *mockcaptureSync_exportSyncFD_Call {
	_c.Call.Return(n, result)
	return _c
}

func (_c *mockcaptureSync_exportSyncFD_Call) RunAndReturn(run func(s vulkan.Semaphore) (int32, vulkan.Result)) *mockcaptureSync_exportSyncFD_Call {
	_c.Call.Return(run)
	return _c
}

// fenceStatus provides a mock function for the type mockcaptureSync
func (_mock *mockcaptureSync) fenceStatus(f vulkan.Fence) vulkan.Result {
	ret := _mock.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for fenceStatus")
	}

	var r0 vulkan.Result
	if returnFunc, ok := ret.Get(0).(func(vulkan.Fence) vulkan.Result); ok {
		r0 = returnFunc(f)
	} else {
		r0 = ret.Get(0).(vulkan.Result)
	}
	return r0
}

// mockcaptureSync_fenceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'fenceStatus'
type mockcaptureSync_fenceStatus_Call struct {
	*mock.Call
}

// fenceStatus is a helper method to define mock.On call
//   - f vulkan.Fence
func (_e *mockcaptureSync_Expecter) fenceStatus(f any) *mockcaptureSync_fenceStatus_Call {
	return &mockcaptureSync_fenceStatus_Call{Call: _e.mock.On("fenceStatus", f)}
}

func (_c *mockcaptureSync_fenceStatus_Call) Run(run func(f vulkan.Fence)) *mockcaptureSync_fenceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 vulkan.Fence
		if args[0] != nil {
			arg0 = args[0].(vulkan.Fence)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcaptureSync_fenceStatus_Call) Return(result vulkan.Result) *mockcaptureSync_fenceStatus_Call {
	_c.Call.Return(result)
	return _c
}

func (_c *mockcaptureSync_fenceStatus_Call) RunAndReturn(run func(f vulkan.Fence) vulkan.Result) *mockcaptureSync_fenceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newSemaphore provides a mock function for the type mockcaptureSync
func (_mock *mockcaptureSync) newSemaphore() (vulkan.Semaphore, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for newSemaphore")
	}

	var r0 vulkan.Semaphore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (vulkan.Semaphore, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() vulkan.Semaphore); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(vulkan.Semaphore)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcaptureSync_newSemaphore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'newSemaphore'
type mockcaptureSync_newSemaphore_Call struct {
	*mock.Call
}

// newSemaphore is a helper method to define mock.On call
func (_e *mockcaptureSync_Expecter) newSemaphore() *mockcaptureSync_newSemaphore_Call {
	return &mockcaptureSync_newSemaphore_Call{Call: _e.mock.On("newSemaphore")}
}

func (_c *mockcaptureSync_newSemaphore_Call) Run(run func()) *mockcaptureSync_newSemaphore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcaptureSync_newSemaphore_Call) Return(semaphore vulkan.Semaphore, err error) *mockcaptureSync_newSemaphore_Call {
	_c.Call.Return(semaphore, err)
	return _c
}

func (_c *mockcaptureSync_newSemaphore_Call) RunAndReturn(run func() (vulkan.Semaphore, error)) *mockcaptureSync_newSemaphore_Call {
	_c.Call.Return(run)
	return _c
}

// resetFence provides a mock function for the type mockcaptureSync
func (_mock *mockcaptureSync) resetFence(f vulkan.Fence) vulkan.Result {
	ret := _mock.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for resetFence")
	}

	var r0 vulkan.Result
	if returnFunc, ok := ret.Get(0).(func(vulkan.Fence) vulkan.Result); ok {
		r0 = returnFunc(f)
	} else {
		r0 = ret.Get(0).(vulkan.Result)
	}
	return r0
}

// mockcaptureSync_resetFence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'resetFence'
type mockcaptureSync_resetFence_Call struct {
	*mock.Call
}

// resetFence is a helper method to define mock.On call
//   - f vulkan.Fence
func (_e *mockcaptureSync_Expecter) resetFence(f any) *mockcaptureSync_resetFence_Call {
	return &mockcaptureSync_resetFence_Call{Call: _e.mock.On("resetFence", f)}
}

func (_c *mockcaptureSync_resetFence_Call) Run(run func(f vulkan.Fence)) *mockcaptureSync_resetFence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 vulkan.Fence
		if args[0] != nil {
			arg0 = args[0].(vulkan.Fence)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcaptureSync_resetFence_Call) Return(result vulkan.Result) *mockcaptureSync_resetFence_Call {
	_c.Call.Return(result)
	return _c
}

func (_c *mockcaptureSync_resetFence_Call) RunAndReturn(run func(f vulkan.Fence) vulkan.Result) *mockcaptureSync_resetFence_Call {
	_c.Call.Return(run)
	return _c
}
