// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package seat

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockdisabler creates a new instance of mockdisabler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdisabler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdisabler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockdisabler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockdisabler is an autogenerated mock type for the disabler type
type mockdisabler struct {
	mock.Mock
}

type mockdisabler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdisabler) EXPECT() *mockdisabler_Expecter {
	return &mockdisabler_Expecter{mock: &_m.Mock}
}

// disable provides a mock function for the type mockdisabler
func (_mock *mockdisabler) disable() {
	_mock.Called()
	return
}

// mockdisabler_disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'disable'
type mockdisabler_disable_Call struct {
	*mock.Call
}

// disable is a helper method to define mock.On call
func (_e *mockdisabler_Expecter) disable() *mockdisabler_disable_Call {
	return &mockdisabler_disable_Call{Call: _e.mock.On("disable")}
}

func (_c *mockdisabler_disable_Call) Run(run func()) *mockdisabler_disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockdisabler_disable_Call) Return() *mockdisabler_disable_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockdisabler_disable_Call) RunAndReturn(run func()) *mockdisabler_disable_Call {
	_c.Run(run)
	return _c
}
