// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wayland

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// newMockpeerExe creates a new instance of mockpeerExe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockpeerExe(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockpeerExe {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockpeerExe{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockpeerExe is an autogenerated mock type for the peerExe type
type mockpeerExe struct {
	mock.Mock
}

type mockpeerExe_Expecter struct {
	mock *mock.Mock
}

func (_m *mockpeerExe) EXPECT() *mockpeerExe_Expecter {
	return &mockpeerExe_Expecter{mock: &_m.Mock}
}

// Exe provides a mock function for the type mockpeerExe
func (_mock *mockpeerExe) Exe(pidfd *os.File) (string, int, error) {
	ret := _mock.Called(pidfd)

	if len(ret) == 0 {
		panic("no return value specified for Exe")
	}

	var r0 string
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*os.File) (string, int, error)); ok {
		return returnFunc(pidfd)
	}
	if returnFunc, ok := ret.Get(0).(func(*os.File) string); ok {
		r0 = returnFunc(pidfd)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*os.File) int); ok {
		r1 = returnFunc(pidfd)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(*os.File) error); ok {
		r2 = returnFunc(pidfd)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockpeerExe_Exe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exe'
type mockpeerExe_Exe_Call struct {
	*mock.Call
}

// Exe is a helper method to define mock.On call
//   - pidfd *os.File
func (_e *mockpeerExe_Expecter) Exe(pidfd any) *mockpeerExe_Exe_Call {
	return &mockpeerExe_Exe_Call{Call: _e.mock.On("Exe", pidfd)}
}

func (_c *mockpeerExe_Exe_Call) Run(run func(pidfd *os.File)) *mockpeerExe_Exe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *os.File
		if args[0] != nil {
			arg0 = args[0].(*os.File)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockpeerExe_Exe_Call) Return(exe string, pid int, err error) *mockpeerExe_Exe_Call {
	_c.Call.Return(exe, pid, err)
	return _c
}

func (_c *mockpeerExe_Exe_Call) RunAndReturn(run func(pidfd *os.File) (string, int, error)) *mockpeerExe_Exe_Call {
	_c.Call.Return(run)
	return _c
}

// Pidfd provides a mock function for the type mockpeerExe
func (_mock *mockpeerExe) Pidfd(sockFD int) (*os.File, error) {
	ret := _mock.Called(sockFD)

	if len(ret) == 0 {
		panic("no return value specified for Pidfd")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*os.File, error)); ok {
		return returnFunc(sockFD)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *os.File); ok {
		r0 = returnFunc(sockFD)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(sockFD)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockpeerExe_Pidfd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pidfd'
type mockpeerExe_Pidfd_Call struct {
	*mock.Call
}

// Pidfd is a helper method to define mock.On call
//   - sockFD int
func (_e *mockpeerExe_Expecter) Pidfd(sockFD any) *mockpeerExe_Pidfd_Call {
	return &mockpeerExe_Pidfd_Call{Call: _e.mock.On("Pidfd", sockFD)}
}

func (_c *mockpeerExe_Pidfd_Call) Run(run func(sockFD int)) *mockpeerExe_Pidfd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockpeerExe_Pidfd_Call) Return(file *os.File, err error) *mockpeerExe_Pidfd_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *mockpeerExe_Pidfd_Call) RunAndReturn(run func(sockFD int) (*os.File, error)) *mockpeerExe_Pidfd_Call {
	_c.Call.Return(run)
	return _c
}
