// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wayland

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockprocEnv creates a new instance of mockprocEnv. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprocEnv(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprocEnv {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockprocEnv{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockprocEnv is an autogenerated mock type for the procEnv type
type mockprocEnv struct {
	mock.Mock
}

type mockprocEnv_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprocEnv) EXPECT() *mockprocEnv_Expecter {
	return &mockprocEnv_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type mockprocEnv
func (_mock *mockprocEnv) Lookup(pid int, key string) (string, bool) {
	ret := _mock.Called(pid, key)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(int, string) (string, bool)); ok {
		return returnFunc(pid, key)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) string); ok {
		r0 = returnFunc(pid, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) bool); ok {
		r1 = returnFunc(pid, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// mockprocEnv_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type mockprocEnv_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - pid int
//   - key string
func (_e *mockprocEnv_Expecter) Lookup(pid any, key any) *mockprocEnv_Lookup_Call {
	return &mockprocEnv_Lookup_Call{Call: _e.mock.On("Lookup", pid, key)}
}

func (_c *mockprocEnv_Lookup_Call) Run(run func(pid int, key string)) *mockprocEnv_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockprocEnv_Lookup_Call) Return(s string, b bool) *mockprocEnv_Lookup_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *mockprocEnv_Lookup_Call) RunAndReturn(run func(pid int, key string) (string, bool)) *mockprocEnv_Lookup_Call {
	_c.Call.Return(run)
	return _c
}
