// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wayland

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// newMocksyncobjDevice creates a new instance of mocksyncobjDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksyncobjDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksyncobjDevice {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mocksyncobjDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mocksyncobjDevice is an autogenerated mock type for the syncobjDevice type
type mocksyncobjDevice struct {
	mock.Mock
}

type mocksyncobjDevice_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksyncobjDevice) EXPECT() *mocksyncobjDevice_Expecter {
	return &mocksyncobjDevice_Expecter{mock: &_m.Mock}
}

// destroy provides a mock function for the type mocksyncobjDevice
func (_mock *mocksyncobjDevice) destroy(h uint32) error {
	ret := _mock.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = returnFunc(h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksyncobjDevice_destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'destroy'
type mocksyncobjDevice_destroy_Call struct {
	*mock.Call
}

// destroy is a helper method to define mock.On call
//   - h uint32
func (_e *mocksyncobjDevice_Expecter) destroy(h any) *mocksyncobjDevice_destroy_Call {
	return &mocksyncobjDevice_destroy_Call{Call: _e.mock.On("destroy", h)}
}

func (_c *mocksyncobjDevice_destroy_Call) Run(run func(h uint32)) *mocksyncobjDevice_destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksyncobjDevice_destroy_Call) Return(err error) *mocksyncobjDevice_destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksyncobjDevice_destroy_Call) RunAndReturn(run func(h uint32) error) *mocksyncobjDevice_destroy_Call {
	_c.Call.Return(run)
	return _c
}

// eventfd provides a mock function for the type mocksyncobjDevice
func (_mock *mocksyncobjDevice) eventfd(h uint32, point uint64, efd int) error {
	ret := _mock.Called(h, point, efd)

	if len(ret) == 0 {
		panic("no return value specified for eventfd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32, uint64, int) error); ok {
		r0 = returnFunc(h, point, efd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksyncobjDevice_eventfd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'eventfd'
type mocksyncobjDevice_eventfd_Call struct {
	*mock.Call
}

// eventfd is a helper method to define mock.On call
//   - h uint32
//   - point uint64
//   - efd int
func (_e *mocksyncobjDevice_Expecter) eventfd(h any, point any, efd any) *mocksyncobjDevice_eventfd_Call {
	return &mocksyncobjDevice_eventfd_Call{Call: _e.mock.On("eventfd", h, point, efd)}
}

func (_c *mocksyncobjDevice_eventfd_Call) Run(run func(h uint32, point uint64, efd int)) *mocksyncobjDevice_eventfd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mocksyncobjDevice_eventfd_Call) Return(err error) *mocksyncobjDevice_eventfd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksyncobjDevice_eventfd_Call) RunAndReturn(run func(h uint32, point uint64, efd int) error) *mocksyncobjDevice_eventfd_Call {
	_c.Call.Return(run)
	return _c
}

// exportSyncFile provides a mock function for the type mocksyncobjDevice
func (_mock *mocksyncobjDevice) exportSyncFile(h uint32, point uint64) (*os.File, error) {
	ret := _mock.Called(h, point)

	if len(ret) == 0 {
		panic("no return value specified for exportSyncFile")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32, uint64) (*os.File, error)); ok {
		return returnFunc(h, point)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32, uint64) *os.File); ok {
		r0 = returnFunc(h, point)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32, uint64) error); ok {
		r1 = returnFunc(h, point)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksyncobjDevice_exportSyncFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'exportSyncFile'
type mocksyncobjDevice_exportSyncFile_Call struct {
	*mock.Call
}

// exportSyncFile is a helper method to define mock.On call
//   - h uint32
//   - point uint64
func (_e *mocksyncobjDevice_Expecter) exportSyncFile(h any, point any) *mocksyncobjDevice_exportSyncFile_Call {
	return &mocksyncobjDevice_exportSyncFile_Call{Call: _e.mock.On("exportSyncFile", h, point)}
}

func (_c *mocksyncobjDevice_exportSyncFile_Call) Run(run func(h uint32, point uint64)) *mocksyncobjDevice_exportSyncFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksyncobjDevice_exportSyncFile_Call) Return(file *os.File, err error) *mocksyncobjDevice_exportSyncFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *mocksyncobjDevice_exportSyncFile_Call) RunAndReturn(run func(h uint32, point uint64) (*os.File, error)) *mocksyncobjDevice_exportSyncFile_Call {
	_c.Call.Return(run)
	return _c
}

// fdToHandle provides a mock function for the type mocksyncobjDevice
func (_mock *mocksyncobjDevice) fdToHandle(fd int) (uint32, error) {
	ret := _mock.Called(fd)

	if len(ret) == 0 {
		panic("no return value specified for fdToHandle")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (uint32, error)); ok {
		return returnFunc(fd)
	}
	if returnFunc, ok := ret.Get(0).(func(int) uint32); ok {
		r0 = returnFunc(fd)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(fd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksyncobjDevice_fdToHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'fdToHandle'
type mocksyncobjDevice_fdToHandle_Call struct {
	*mock.Call
}

// fdToHandle is a helper method to define mock.On call
//   - fd int
func (_e *mocksyncobjDevice_Expecter) fdToHandle(fd any) *mocksyncobjDevice_fdToHandle_Call {
	return &mocksyncobjDevice_fdToHandle_Call{Call: _e.mock.On("fdToHandle", fd)}
}

func (_c *mocksyncobjDevice_fdToHandle_Call) Run(run func(fd int)) *mocksyncobjDevice_fdToHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksyncobjDevice_fdToHandle_Call) Return(v uint32, err error) *mocksyncobjDevice_fdToHandle_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mocksyncobjDevice_fdToHandle_Call) RunAndReturn(run func(fd int) (uint32, error)) *mocksyncobjDevice_fdToHandle_Call {
	_c.Call.Return(run)
	return _c
}

// signal provides a mock function for the type mocksyncobjDevice
func (_mock *mocksyncobjDevice) signal(h uint32, point uint64) error {
	ret := _mock.Called(h, point)

	if len(ret) == 0 {
		panic("no return value specified for signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32, uint64) error); ok {
		r0 = returnFunc(h, point)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksyncobjDevice_signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'signal'
type mocksyncobjDevice_signal_Call struct {
	*mock.Call
}

// signal is a helper method to define mock.On call
//   - h uint32
//   - point uint64
func (_e *mocksyncobjDevice_Expecter) signal(h any, point any) *mocksyncobjDevice_signal_Call {
	return &mocksyncobjDevice_signal_Call{Call: _e.mock.On("signal", h, point)}
}

func (_c *mocksyncobjDevice_signal_Call) Run(run func(h uint32, point uint64)) *mocksyncobjDevice_signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksyncobjDevice_signal_Call) Return(err error) *mocksyncobjDevice_signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksyncobjDevice_signal_Call) RunAndReturn(run func(h uint32, point uint64) error) *mocksyncobjDevice_signal_Call {
	_c.Call.Return(run)
	return _c
}
