// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package drm

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockcursorPlane creates a new instance of mockcursorPlane. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcursorPlane(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcursorPlane {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockcursorPlane{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockcursorPlane is an autogenerated mock type for the cursorPlane type
type mockcursorPlane struct {
	mock.Mock
}

type mockcursorPlane_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcursorPlane) EXPECT() *mockcursorPlane_Expecter {
	return &mockcursorPlane_Expecter{mock: &_m.Mock}
}

// Set provides a mock function for the type mockcursorPlane
func (_mock *mockcursorPlane) Set(v *modeCursor2) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*modeCursor2) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockcursorPlane_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockcursorPlane_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - v *modeCursor2
func (_e *mockcursorPlane_Expecter) Set(v any) *mockcursorPlane_Set_Call {
	return &mockcursorPlane_Set_Call{Call: _e.mock.On("Set", v)}
}

func (_c *mockcursorPlane_Set_Call) Run(run func(v *modeCursor2)) *mockcursorPlane_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *modeCursor2
		if args[0] != nil {
			arg0 = args[0].(*modeCursor2)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcursorPlane_Set_Call) Return(err error) *mockcursorPlane_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockcursorPlane_Set_Call) RunAndReturn(run func(v *modeCursor2) error) *mockcursorPlane_Set_Call {
	_c.Call.Return(run)
	return _c
}

// WaitVblank provides a mock function for the type mockcursorPlane
func (_mock *mockcursorPlane) WaitVblank() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaitVblank")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockcursorPlane_WaitVblank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitVblank'
type mockcursorPlane_WaitVblank_Call struct {
	*mock.Call
}

// WaitVblank is a helper method to define mock.On call
func (_e *mockcursorPlane_Expecter) WaitVblank() *mockcursorPlane_WaitVblank_Call {
	return &mockcursorPlane_WaitVblank_Call{Call: _e.mock.On("WaitVblank")}
}

func (_c *mockcursorPlane_WaitVblank_Call) Run(run func()) *mockcursorPlane_WaitVblank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockcursorPlane_WaitVblank_Call) Return(err error) *mockcursorPlane_WaitVblank_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockcursorPlane_WaitVblank_Call) RunAndReturn(run func() error) *mockcursorPlane_WaitVblank_Call {
	_c.Call.Return(run)
	return _c
}
