// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package drm

import (
	"os"

	"github.com/bnema/neferwl/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// newMockkms creates a new instance of mockkms. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockkms(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockkms {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockkms{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockkms is an autogenerated mock type for the kms type
type mockkms struct {
	mock.Mock
}

type mockkms_Expecter struct {
	mock *mock.Mock
}

func (_m *mockkms) EXPECT() *mockkms_Expecter {
	return &mockkms_Expecter{mock: &_m.Mock}
}

// addFB provides a mock function for the type mockkms
func (_mock *mockkms) addFB(b *ports.DMABuf, format uint32) (uint32, error) {
	ret := _mock.Called(b, format)

	if len(ret) == 0 {
		panic("no return value specified for addFB")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ports.DMABuf, uint32) (uint32, error)); ok {
		return returnFunc(b, format)
	}
	if returnFunc, ok := ret.Get(0).(func(*ports.DMABuf, uint32) uint32); ok {
		r0 = returnFunc(b, format)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(*ports.DMABuf, uint32) error); ok {
		r1 = returnFunc(b, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_addFB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'addFB'
type mockkms_addFB_Call struct {
	*mock.Call
}

// addFB is a helper method to define mock.On call
//   - b *ports.DMABuf
//   - format uint32
func (_e *mockkms_Expecter) addFB(b any, format any) *mockkms_addFB_Call {
	return &mockkms_addFB_Call{Call: _e.mock.On("addFB", b, format)}
}

func (_c *mockkms_addFB_Call) Run(run func(b *ports.DMABuf, format uint32)) *mockkms_addFB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ports.DMABuf
		if args[0] != nil {
			arg0 = args[0].(*ports.DMABuf)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockkms_addFB_Call) Return(v uint32, err error) *mockkms_addFB_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mockkms_addFB_Call) RunAndReturn(run func(b *ports.DMABuf, format uint32) (uint32, error)) *mockkms_addFB_Call {
	_c.Call.Return(run)
	return _c
}

// commit provides a mock function for the type mockkms
func (_mock *mockkms) commit(req *atomicReq, flags uint32, userData uint64) error {
	ret := _mock.Called(req, flags, userData)

	if len(ret) == 0 {
		panic("no return value specified for commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*atomicReq, uint32, uint64) error); ok {
		r0 = returnFunc(req, flags, userData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkms_commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'commit'
type mockkms_commit_Call struct {
	*mock.Call
}

// commit is a helper method to define mock.On call
//   - req *atomicReq
//   - flags uint32
//   - userData uint64
func (_e *mockkms_Expecter) commit(req any, flags any, userData any) *mockkms_commit_Call {
	return &mockkms_commit_Call{Call: _e.mock.On("commit", req, flags, userData)}
}

func (_c *mockkms_commit_Call) Run(run func(req *atomicReq, flags uint32, userData uint64)) *mockkms_commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *atomicReq
		if args[0] != nil {
			arg0 = args[0].(*atomicReq)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockkms_commit_Call) Return(err error) *mockkms_commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkms_commit_Call) RunAndReturn(run func(req *atomicReq, flags uint32, userData uint64) error) *mockkms_commit_Call {
	_c.Call.Return(run)
	return _c
}

// connector provides a mock function for the type mockkms
func (_mock *mockkms) connector(id uint32) (connector, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for connector")
	}

	var r0 connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32) (connector, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32) connector); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(connector)
	}
	if returnFunc, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_connector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'connector'
type mockkms_connector_Call struct {
	*mock.Call
}

// connector is a helper method to define mock.On call
//   - id uint32
func (_e *mockkms_Expecter) connector(id any) *mockkms_connector_Call {
	return &mockkms_connector_Call{Call: _e.mock.On("connector", id)}
}

func (_c *mockkms_connector_Call) Run(run func(id uint32)) *mockkms_connector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_connector_Call) Return(connectorMoqParam connector, err error) *mockkms_connector_Call {
	_c.Call.Return(connectorMoqParam, err)
	return _c
}

func (_c *mockkms_connector_Call) RunAndReturn(run func(id uint32) (connector, error)) *mockkms_connector_Call {
	_c.Call.Return(run)
	return _c
}

// createBlob provides a mock function for the type mockkms
func (_mock *mockkms) createBlob(data []byte) (uint32, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for createBlob")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (uint32, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) uint32); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_createBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createBlob'
type mockkms_createBlob_Call struct {
	*mock.Call
}

// createBlob is a helper method to define mock.On call
//   - data []byte
func (_e *mockkms_Expecter) createBlob(data any) *mockkms_createBlob_Call {
	return &mockkms_createBlob_Call{Call: _e.mock.On("createBlob", data)}
}

func (_c *mockkms_createBlob_Call) Run(run func(data []byte)) *mockkms_createBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_createBlob_Call) Return(v uint32, err error) *mockkms_createBlob_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mockkms_createBlob_Call) RunAndReturn(run func(data []byte) (uint32, error)) *mockkms_createBlob_Call {
	_c.Call.Return(run)
	return _c
}

// createLease provides a mock function for the type mockkms
func (_mock *mockkms) createLease(objects []uint32) (*os.File, uint32, error) {
	ret := _mock.Called(objects)

	if len(ret) == 0 {
		panic("no return value specified for createLease")
	}

	var r0 *os.File
	var r1 uint32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]uint32) (*os.File, uint32, error)); ok {
		return returnFunc(objects)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint32) *os.File); ok {
		r0 = returnFunc(objects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint32) uint32); ok {
		r1 = returnFunc(objects)
	} else {
		r1 = ret.Get(1).(uint32)
	}
	if returnFunc, ok := ret.Get(2).(func([]uint32) error); ok {
		r2 = returnFunc(objects)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockkms_createLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createLease'
type mockkms_createLease_Call struct {
	*mock.Call
}

// createLease is a helper method to define mock.On call
//   - objects []uint32
func (_e *mockkms_Expecter) createLease(objects any) *mockkms_createLease_Call {
	return &mockkms_createLease_Call{Call: _e.mock.On("createLease", objects)}
}

func (_c *mockkms_createLease_Call) Run(run func(objects []uint32)) *mockkms_createLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint32
		if args[0] != nil {
			arg0 = args[0].([]uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_createLease_Call) Return(file *os.File, v uint32, err error) *mockkms_createLease_Call {
	_c.Call.Return(file, v, err)
	return _c
}

func (_c *mockkms_createLease_Call) RunAndReturn(run func(objects []uint32) (*os.File, uint32, error)) *mockkms_createLease_Call {
	_c.Call.Return(run)
	return _c
}

// destroyBlob provides a mock function for the type mockkms
func (_mock *mockkms) destroyBlob(id uint32) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for destroyBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkms_destroyBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'destroyBlob'
type mockkms_destroyBlob_Call struct {
	*mock.Call
}

// destroyBlob is a helper method to define mock.On call
//   - id uint32
func (_e *mockkms_Expecter) destroyBlob(id any) *mockkms_destroyBlob_Call {
	return &mockkms_destroyBlob_Call{Call: _e.mock.On("destroyBlob", id)}
}

func (_c *mockkms_destroyBlob_Call) Run(run func(id uint32)) *mockkms_destroyBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_destroyBlob_Call) Return(err error) *mockkms_destroyBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkms_destroyBlob_Call) RunAndReturn(run func(id uint32) error) *mockkms_destroyBlob_Call {
	_c.Call.Return(run)
	return _c
}

// getBlob provides a mock function for the type mockkms
func (_mock *mockkms) getBlob(id uint32) ([]byte, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for getBlob")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32) ([]byte, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32) []byte); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_getBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getBlob'
type mockkms_getBlob_Call struct {
	*mock.Call
}

// getBlob is a helper method to define mock.On call
//   - id uint32
func (_e *mockkms_Expecter) getBlob(id any) *mockkms_getBlob_Call {
	return &mockkms_getBlob_Call{Call: _e.mock.On("getBlob", id)}
}

func (_c *mockkms_getBlob_Call) Run(run func(id uint32)) *mockkms_getBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_getBlob_Call) Return(bytes []byte, err error) *mockkms_getBlob_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockkms_getBlob_Call) RunAndReturn(run func(id uint32) ([]byte, error)) *mockkms_getBlob_Call {
	_c.Call.Return(run)
	return _c
}

// objProps provides a mock function for the type mockkms
func (_mock *mockkms) objProps(obj uint32, typ uint32) (map[string][2]uint64, error) {
	ret := _mock.Called(obj, typ)

	if len(ret) == 0 {
		panic("no return value specified for objProps")
	}

	var r0 map[string][2]uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32, uint32) (map[string][2]uint64, error)); ok {
		return returnFunc(obj, typ)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32, uint32) map[string][2]uint64); ok {
		r0 = returnFunc(obj, typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][2]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32, uint32) error); ok {
		r1 = returnFunc(obj, typ)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_objProps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'objProps'
type mockkms_objProps_Call struct {
	*mock.Call
}

// objProps is a helper method to define mock.On call
//   - obj uint32
//   - typ uint32
func (_e *mockkms_Expecter) objProps(obj any, typ any) *mockkms_objProps_Call {
	return &mockkms_objProps_Call{Call: _e.mock.On("objProps", obj, typ)}
}

func (_c *mockkms_objProps_Call) Run(run func(obj uint32, typ uint32)) *mockkms_objProps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockkms_objProps_Call) Return(stringToUint64s map[string][2]uint64, err error) *mockkms_objProps_Call {
	_c.Call.Return(stringToUint64s, err)
	return _c
}

func (_c *mockkms_objProps_Call) RunAndReturn(run func(obj uint32, typ uint32) (map[string][2]uint64, error)) *mockkms_objProps_Call {
	_c.Call.Return(run)
	return _c
}

// pickCrtc provides a mock function for the type mockkms
func (_mock *mockkms) pickCrtc(c connector, crtcs []uint32, used map[uint32]bool) (uint32, error) {
	ret := _mock.Called(c, crtcs, used)

	if len(ret) == 0 {
		panic("no return value specified for pickCrtc")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(connector, []uint32, map[uint32]bool) (uint32, error)); ok {
		return returnFunc(c, crtcs, used)
	}
	if returnFunc, ok := ret.Get(0).(func(connector, []uint32, map[uint32]bool) uint32); ok {
		r0 = returnFunc(c, crtcs, used)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(connector, []uint32, map[uint32]bool) error); ok {
		r1 = returnFunc(c, crtcs, used)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_pickCrtc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'pickCrtc'
type mockkms_pickCrtc_Call struct {
	*mock.Call
}

// pickCrtc is a helper method to define mock.On call
//   - c connector
//   - crtcs []uint32
//   - used map[uint32]bool
func (_e *mockkms_Expecter) pickCrtc(c any, crtcs any, used any) *mockkms_pickCrtc_Call {
	return &mockkms_pickCrtc_Call{Call: _e.mock.On("pickCrtc", c, crtcs, used)}
}

func (_c *mockkms_pickCrtc_Call) Run(run func(c connector, crtcs []uint32, used map[uint32]bool)) *mockkms_pickCrtc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connector
		if args[0] != nil {
			arg0 = args[0].(connector)
		}
		var arg1 []uint32
		if args[1] != nil {
			arg1 = args[1].([]uint32)
		}
		var arg2 map[uint32]bool
		if args[2] != nil {
			arg2 = args[2].(map[uint32]bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockkms_pickCrtc_Call) Return(v uint32, err error) *mockkms_pickCrtc_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mockkms_pickCrtc_Call) RunAndReturn(run func(c connector, crtcs []uint32, used map[uint32]bool) (uint32, error)) *mockkms_pickCrtc_Call {
	_c.Call.Return(run)
	return _c
}

// planes provides a mock function for the type mockkms
func (_mock *mockkms) planes() ([]planeRes, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for planes")
	}

	var r0 []planeRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]planeRes, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []planeRes); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]planeRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockkms_planes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'planes'
type mockkms_planes_Call struct {
	*mock.Call
}

// planes is a helper method to define mock.On call
func (_e *mockkms_Expecter) planes() *mockkms_planes_Call {
	return &mockkms_planes_Call{Call: _e.mock.On("planes")}
}

func (_c *mockkms_planes_Call) Run(run func()) *mockkms_planes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockkms_planes_Call) Return(planeResMoqParams []planeRes, err error) *mockkms_planes_Call {
	_c.Call.Return(planeResMoqParams, err)
	return _c
}

func (_c *mockkms_planes_Call) RunAndReturn(run func() ([]planeRes, error)) *mockkms_planes_Call {
	_c.Call.Return(run)
	return _c
}

// resources provides a mock function for the type mockkms
func (_mock *mockkms) resources() ([]uint32, []uint32, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for resources")
	}

	var r0 []uint32
	var r1 []uint32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]uint32, []uint32, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []uint32); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []uint32); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]uint32)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockkms_resources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'resources'
type mockkms_resources_Call struct {
	*mock.Call
}

// resources is a helper method to define mock.On call
func (_e *mockkms_Expecter) resources() *mockkms_resources_Call {
	return &mockkms_resources_Call{Call: _e.mock.On("resources")}
}

func (_c *mockkms_resources_Call) Run(run func()) *mockkms_resources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockkms_resources_Call) Return(uint32s []uint32, uint32s1 []uint32, err error) *mockkms_resources_Call {
	_c.Call.Return(uint32s, uint32s1, err)
	return _c
}

func (_c *mockkms_resources_Call) RunAndReturn(run func() ([]uint32, []uint32, error)) *mockkms_resources_Call {
	_c.Call.Return(run)
	return _c
}

// revokeLease provides a mock function for the type mockkms
func (_mock *mockkms) revokeLease(id uint32) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for revokeLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkms_revokeLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'revokeLease'
type mockkms_revokeLease_Call struct {
	*mock.Call
}

// revokeLease is a helper method to define mock.On call
//   - id uint32
func (_e *mockkms_Expecter) revokeLease(id any) *mockkms_revokeLease_Call {
	return &mockkms_revokeLease_Call{Call: _e.mock.On("revokeLease", id)}
}

func (_c *mockkms_revokeLease_Call) Run(run func(id uint32)) *mockkms_revokeLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_revokeLease_Call) Return(err error) *mockkms_revokeLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkms_revokeLease_Call) RunAndReturn(run func(id uint32) error) *mockkms_revokeLease_Call {
	_c.Call.Return(run)
	return _c
}

// rmFB provides a mock function for the type mockkms
func (_mock *mockkms) rmFB(id uint32) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for rmFB")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockkms_rmFB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'rmFB'
type mockkms_rmFB_Call struct {
	*mock.Call
}

// rmFB is a helper method to define mock.On call
//   - id uint32
func (_e *mockkms_Expecter) rmFB(id any) *mockkms_rmFB_Call {
	return &mockkms_rmFB_Call{Call: _e.mock.On("rmFB", id)}
}

func (_c *mockkms_rmFB_Call) Run(run func(id uint32)) *mockkms_rmFB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockkms_rmFB_Call) Return(err error) *mockkms_rmFB_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockkms_rmFB_Call) RunAndReturn(run func(id uint32) error) *mockkms_rmFB_Call {
	_c.Call.Return(run)
	return _c
}
